version: "3.8"

services:
  countryservice:
    container_name: countryservice
    image: gariptipici/countryservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"