name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=gariptipici_countryservice -Dsonar.organization=gariptipici -Dsonar.host.url=https://sonarcloud.io

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/countryservice

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/countryservice

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: "countryservice"
            heroku_email: "gariptipici@gmail.com"

